### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by vilmibm** [modgethanc/ttbp#15]
this issue covers:

- creating a setup.py
- referencing things installed via pip (`inflect`)
- inlining the `chatter` functions so they live inside this project
- creating entry points (`ttbp` and `feels`) so when the project is installed you get nice scripts for running it

i'm going to start the setup.py at version 0.9.3

**Comment by modgethanc** [comment]
(lol disregard that commit about disabling global feels writing, that was a typo)

going to close this issue because setup.py seems to be up and running now!
