### ISSUE TITLE
permission error for global feels index.html writing

### ISSUE THREAD

**Issue by modgethanc** [modgethanc/ttbp#19]
after saving a new post: 
>\> posted to https://tilde.town/~endorphant/blog/index.html
\> thanks for sharing your feels!
Traceback (most recent call last):
  File "/usr/local/bin/feels", line 9, in <module>
    load_entry_point('ttbp', 'console_scripts', 'feels')()
  File "/home/vilmibm/src/ttbp/ttbp/ttbp.py", line 188, in start
    print(main_menu())
  File "/home/vilmibm/src/ttbp/ttbp/ttbp.py", line 444, in main_menu
    core.www_neighbors()
  File "/home/vilmibm/src/ttbp/ttbp/core.py", line 403, in www_neighbors
    write_global_feed(sortedUsers)
  File "/home/vilmibm/src/ttbp/ttbp/core.py", line 212, in write_global_feed
    outfile = open(FEED, "w")
IOError: [Errno 13] Permission denied: '/var/global/ttbp/www/index.html'

**Comment by vilmibm** [comment]
fixed in #20

**Comment by modgethanc** [comment]
gonna reopen this because it's still kind of buggy; even after the last update, i'm getting:
>\> posted to https://tilde.town/~endorphant/blog/index.html
>\> thanks for sharing your feels!
>
>chmod: changing permissions of '/var/global/ttbp/www/index.html': Operation not permitted
>you're at ttbp home. remember, you can always press <ctrl-c> to come back here.

so it's not crashing, but also dumping this error. currently, that file is rw-rw-rw, but owned by vilmibm; since it's world-writeable now, maybe it's okay to not have a chmod every time it needs to be updated?

(just dumping this note here because i'm too sleepy to look into it now but i'll figure this out later)

**Comment by vilmibm** [comment]
ah crap yeah i think chmod only works if you own the file. shit -- i think this might explain the problems with the wiki too. sorry about that!

i'll think on a better approach to shared resources.

**Comment by modgethanc** [comment]
okay, this is fixed for ttbp at least, so you can pull the current master whenever you please!
