### ISSUE TITLE
Navigation error in [3] browse global feels

### ISSUE THREAD

**Issue by login000** [modgethanc/ttbp#38]
Steps to reproduce:
1. Open new terminal window.
2. SSH into tilde.town.
3. Type 'feels' (without quotes) and press enter.
4. Press enter.
5. Type 3 and press enter.
6. Type 'd' and press enter.
7. Type any single digit (0-9, inclusive) and press enter.
8. Press 'q' (without quotes).

Expected behaviour: Will return to recent global entries on page 2.
Actual behaviour: Returns to recent global entries on page 1.

**Comment by modgethanc** [comment]
thanks for reporting this, it's helpful to have these steps to reproduce! #29 is the main issue for this, so i'll reference your report there and close this issue.
